services:
  app:
    container_name: rust_fullstack_api
    build:
      context: . # Build context is the root directory
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/test_api
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_api
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
